[versions]
activity = "1.11.0"
aboutlibraries = "13.1.0"
android-device-names = "2.1.1"
annotation = "1.9.1"
appcompat = "1.7.1"
agp = "8.13.0"
billing-ktx = "8.0.0"
circleindicator = "2.1.6"
compose = "2025.10.01"
compose-lint-checks = "1.4.2"
detekt = "1.23.8"
kotlinx-collections-immutable = "0.4.0"
ksp = "2.2.20-2.0.3"
constraintlayout = "2.2.1"
converter-moshi = "3.0.0"
core-ktx-version = "1.7.0"
desugar-jdk-libs = "2.1.5"
documentfile = "1.1.0"
drawerlayout = "1.2.0"
espresso-core = "3.7.0"
exoplayer-shuttle = "2.14.2-shuttle-16-5"
firebase-bom = "34.5.0"
firebase-crashlytics = "3.0.6"
fluent-system-icons = "1.1.311"
fragment-ktx = "1.8.9"
glide = "5.0.5"
google-services = "4.4.4"
hamcrest-library = "3.0"
hilt-android = "2.57.2"
hilt-compiler = "1.3.0"
hilt-work = "1.3.0"
junit = "4.13.2"
junit-version = "1.3.0"
kotlin = "2.2.21"
kotlinx-coroutines-android = "1.10.2"
kotlinx-coroutines-core = "1.10.2"
kotlinx-coroutines-play-services = "1.10.2"
kotlinx-datetime = "0.7.1"
ktaglib = "1.6.1"
leakcanary-android = "2.14"
lifecycle-common-java8 = "2.9.4"
lifecycle-extensions = "2.2.0"
lifecycle-runtime-ktx = "2.9.4"
lifecycle-viewmodel-compose = "2.9.4"
logging-interceptor = "5.3.0"
material = "1.13.0"
media = "1.7.1"
moshi = "1.15.2"
moshi-adapters = "1.15.2"
moshi-kotlin = "1.15.2"
moshi-kotlin-codegen = "1.15.2"
mpandroidchart = "3.1.0"
nanohttpd-webserver = "2.3.1"
navigation-safe-args-gradle-plugin = "2.9.5"
navigation-ui-ktx = "2.9.5"
noise = "3.0.3"
okhttp = "5.3.0"
okhttp3-integration = "5.0.5"
palette-ktx = "1.0.0"
phrase = "master-SNAPSHOT"
play-services-cast-framework = "22.2.0"
preference-ktx = "1.2.1"
recyclerview = "1.4.0"
recyclerview-fastscroll = "2.0.1"
review = "2.0.2"
room-compiler = "2.8.3"
runner = "1.7.0"
security-crypto = "1.1.0"
semver4j = "3.1.0"
timber = "5.0.1"
viewpager2 = "1.1.0"
work-runtime-ktx = "2.11.0"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
androidx-activity-compose = { module = "androidx.activity:activity-compose"}
androidx-annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.test:core-ktx", version.ref = "core-ktx-version" }
androidx-documentfile = { module = "androidx.documentfile:documentfile", version.ref = "documentfile" }
androidx-drawerlayout = { module = "androidx.drawerlayout:drawerlayout", version.ref = "drawerlayout" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-foundation = { module = "androidx.compose.foundation:foundation" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment-ktx" }
androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "hilt-compiler" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "hilt-work" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "junit-version" }
androidx-lifecycle-common-java8 = { module = "androidx.lifecycle:lifecycle-common-java8", version.ref = "lifecycle-common-java8" }
androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle-viewmodel-compose" }
androidx-material = { module = "androidx.compose.material:material" }
androidx-material3 = { module = "androidx.compose.material3:material3" }
androidx-media = { module = "androidx.media:media", version.ref = "media" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigation-ui-ktx" }
androidx-navigation-safe-args-gradle-plugin = { module = "androidx.navigation:navigation-safe-args-gradle-plugin", version.ref = "navigation-safe-args-gradle-plugin" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigation-ui-ktx" }
androidx-palette-ktx = { module = "androidx.palette:palette-ktx", version.ref = "palette-ktx" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preference-ktx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room-compiler" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room-compiler" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room-compiler" }
androidx-rules = { module = "androidx.test:rules", version.ref = "core-ktx-version" }
androidx-runner = { module = "androidx.test:runner", version.ref = "runner" }
androidx-security-crypto = { module = "androidx.security:security-crypto", version.ref = "security-crypto" }
androidx-ui = { module = "androidx.compose.ui:ui" }
androidx-ui-tooling = { module = "androidx.compose.ui:ui-tooling" }
androidx-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview" }
androidx-viewpager2 = { module = "androidx.viewpager2:viewpager2", version.ref = "viewpager2" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "work-runtime-ktx" }
billingclient-billingKtx = { module = "com.android.billingclient:billing-ktx", version.ref = "billing-ktx" }
compose-lint-checks = { module = "com.slack.lint.compose:compose-lint-checks", version.ref = "compose-lint-checks" }
design-fluentSystemIcons = { module = "com.microsoft.design:fluent-system-icons", version.ref = "fluent-system-icons" }
detekt-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
exoplayer-core = { module = "com.github.timusus.exoplayer:exoplayer-core", version.ref = "exoplayer-shuttle" }
exoplayer-extensionFlac = { module = "com.github.timusus.exoplayer:extension-flac", version.ref = "exoplayer-shuttle" }
exoplayer-extensionOpus = { module = "com.github.timusus.exoplayer:extension-opus", version.ref = "exoplayer-shuttle" }
exoplayer-hls = { module = "com.github.timusus.exoplayer:exoplayer-hls", version.ref = "exoplayer-shuttle" }
firebase-analytics-ktx = { module = "com.google.firebase:firebase-analytics" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebase-bom" }
firebase-config-ktx = { module = "com.google.firebase:firebase-config" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
glide-annotations = { module = "com.github.bumptech.glide:annotations", version.ref = "glide" }
glide-ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
glide-okhttp3Integration = { module = "com.github.bumptech.glide:okhttp3-integration", version.ref = "okhttp3-integration" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
google-play-services-cast-framework = { module = "com.google.android.gms:play-services-cast-framework", version.ref = "play-services-cast-framework" }
google-review = { module = "com.google.android.play:review", version.ref = "review" }
google-review-ktx = { module = "com.google.android.play:review-ktx", version.ref = "review" }
hamcrest-library = { module = "org.hamcrest:hamcrest-library", version.ref = "hamcrest-library" }
hilt-android-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt-android" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt-android" }
hilt = { module = "com.google.dagger:hilt-android", version.ref = "hilt-android" }
jaredrummler-androidDeviceNames = { module = "com.jaredrummler:android-device-names", version.ref = "android-device-names" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlinx-collections-immutable = { module = "org.jetbrains.kotlinx:kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable" }
kotlinx-coroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines-android" }
kotlinx-coroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines-core" }
kotlinx-coroutinesPlayServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinx-coroutines-play-services" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "kotlinx-datetime" }
leakcanary-android = { module = "com.squareup.leakcanary:leakcanary-android", version.ref = "leakcanary-android" }
mikepenz-aboutlibrariesCore = { module = "com.mikepenz:aboutlibraries-core", version.ref = "aboutlibraries" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-adapters = { module = "com.squareup.moshi:moshi-adapters", version.ref = "moshi-adapters" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi-kotlin" }
moshi-kotlinCodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi-kotlin-codegen" }
nanohttpd-webserver = { module = "org.nanohttpd:nanohttpd-webserver", version.ref = "nanohttpd-webserver" }
okhttp3-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "logging-interceptor" }
okhttp3-okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
paramsen-noise = { module = "com.github.timusus:noise", version.ref = "noise" }
philjay-mpAndroidChart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpandroidchart" }
relex-circleindicator = { module = "me.relex:circleindicator", version.ref = "circleindicator" }
retrofit2-converterMoshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "converter-moshi" }
retrofit2-retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "converter-moshi" }
square-phrase = { module = "com.github.square:phrase", version.ref = "phrase" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
timusus-ktaglib = { module = "com.github.timusus:ktaglib", version.ref = "ktaglib" }
timusus-recyclerViewFastScroll = { module = "com.simplecityapps:recyclerview-fastscroll", version.ref = "recyclerview-fastscroll" }
tools-desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
vdurmont-semver4j = { module = "com.vdurmont:semver4j", version.ref = "semver4j" }

[plugins]

aboutlibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "aboutlibraries" }
android-application = { id = "com.android.application", version.ref = "agp" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-android" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
